#!/usr/bin/perl -T

use strict;
use warnings;
use File::Basename;
use lib dirname(__FILE__) . '/../lib';

use EV;
use AnyEvent;
use Data::Dumper;
use YubiAuthd::FileIdentityStore;
use YubiAuthd::AuthenticationSocket;
use YubiAuthd::SynchronizationSocket;
use YubiAuthd::SynchronizationPeer;

my $store = YubiAuthd::FileIdentityStore->new(dirname(__FILE__) . '/../yubiauth');

my $peers = [
    YubiAuthd::SynchronizationPeer->new(
            ip_address  => '::1',
            port        => 16000,
            shared_key  => 'secret_pass_phrase'
            ),
    YubiAuthd::SynchronizationPeer->new(
            ip_address  => '127.0.0.1',
            port        => 16000,
            shared_key  => 'secret_pass_phrase'
            ),
];

my $auth_socket = YubiAuthd::AuthenticationSocket->new(
        socket_path     => "/tmp/yubiauth.sock",
        identity_store  => $store
        );

my $sync_socket = YubiAuthd::SynchronizationSocket->new(
        ip_address      => '::',
        port            => 16000,
        identity_store  => $store,
        peers           => $peers
        );

print "Started!\n";

# Run our event loop
AnyEvent->condvar->recv;
